### ISSUE TITLE
Threshold for not matching any categories

### ISSUE THREAD

**Issue by hydefus** [niiknow/bayes#6]
Hi there

How can I implement a default fallback category based on a threshold parameter ?

For instance given an input text, if none of the categories reach this threshold then the categorize method would return null

How can I interprete the "probabilities" method ?

Thank you!

**Comment by noogen** [comment]
Since this is php7+, we can rewrite the method as follow:
```php
    public function categorize($text, $maxProbability = -INF)
    {
        $that           = $this;
        // $maxProbability = -INF;  // moved up to parameters
        $chosenCategory = null;

        if ($that->totalDocuments > 0) {
            $probabilities = $that->probabilities($text);

            // iterate thru our categories to find the one with max probability
            // for this text
            foreach ($probabilities as $category => $logProbability) {
                if ($logProbability > $maxProbability) {
                    $maxProbability = $logProbability;
                    $chosenCategory = $category;
                }
            }
        }

        return $chosenCategory;
    }
```

Now you can call it with your own $maxProbability parameter.

```php
$result = $bayes->categorize('something', 0.01);
if ($result === null) {
   $result = $someDefaultCategory;
}
```

You're welcome to do a pull request for the change above.

**Comment by hydefus** [comment]
Hi Tom, conceptually that's the idea.

However the algorithm uses the log of the probabilities, so the result is not a rate between 0.0 and 1.0
If i use the exp function, it doesn't work either because there are some non linear transformation in the calculation.

Best regards

**Comment by noogen** [comment]
Closing, too old.
